---
swagger: "2.0"
info:
  x-ibm-name: "hola-mundo"
  title: "Hola Mundo"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/hola-mundo"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions: {}
security: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "https://jsonplaceholder.typicode.com/posts"
  phase: "realized"
paths:
  /path-1:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
